---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: pacman
  namespace: pacman
spec:
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - pacman-app
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
