apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: pacman-sub
  namespace: pacman
  labels:
    app: pacman-app
  annotations:
    apps.open-cluster-management.io/git-path: app-lifecycle/pacman/
    apps.open-cluster-management.io/git-branch: master
spec:
  channel: pacman/pacman-ch
  placement:
    placementRef:
      kind: PlacementRule
      name: pacman-pr
