## This policy creates a development namespace, a role to view pods, and two bindings for users developer and observer
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-develop-conf
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: development-namespace
        spec:
          remediationAction: inform # will be overridden by remediationAction in parent policy
          severity: medium
          namespaceSelector:
            exclude: ["kube-*"]
            include: ["default"]
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: development
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: development-quota
        spec:
          remediationAction: inform # will be overridden by remediationAction in parent policy
          severity: medium
          namespaceSelector:
            exclude: ["kube-*"]
            include: ["default"]
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: ResourceQuota
                metadata:
                  name: core-object-quota
                  namespace: development
                spec:
                  hard:
                    configmaps: "15"
                    persistentvolumeclaims: "5"
                    replicationcontrollers: "40"
                    secrets: "20"
                    services: "20"
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: podview-role
        spec:
          remediationAction: inform # will be overridden by remediationAction in parent policy
          severity: medium
          namespaceSelector:
            exclude: ["kube-*"]
            include: ["default"]
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: Role
                metadata:
                  name: podview
                  namespace: development
                rules:
                - apiGroups:
                  - ""
                  resources:
                  - pods
                  verbs:
                  - get
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: developer-binding
        spec:
          remediationAction: inform # will be overridden by remediationAction in parent policy
          severity: medium
          namespaceSelector:
            exclude: ["kube-*"]
            include: ["default"]
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: RoleBinding
                metadata:
                  name: admin-0
                  namespace: development
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: admin
                subjects:
                - apiGroup: rbac.authorization.k8s.io
                  kind: User
                  name: developer
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: observer-binding
        spec:
          remediationAction: inform # will be overridden by remediationAction in parent policy
          severity: medium
          namespaceSelector:
            exclude: ["kube-*"]
            include: ["default"]
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: RoleBinding
                metadata:
                  name: podview
                  namespace: development
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: Role
                  name: podview
                subjects:
                - apiGroup: rbac.authorization.k8s.io
                  kind: User
                  name: observer

---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-develop-conf
placementRef:
  name: placement-policy-develop-conf
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-develop-conf
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-develop-conf
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: environment, operator: In, values: ["dev"]}

