apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-local-users
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: AC Access Control
    policy.open-cluster-management.io/controls: AC-6 Privilege
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: htpassw-secret
        spec:
          remediationAction: inform # will be overridden by remediationAction in parent policy
          severity: high
          namespaceSelector:
            exclude: ["kube-*"]
            include: ["default"]
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                data:
                  htpasswd: Y2x1c3RlcmFkbWluOiQyeSQwNSQ4cU9IYzk0Y29MWHd2Vmtkd1ZjRS91dWxYVFJBZkpIaXNCYlhIUDdKRS83RzZ3ckhrOUgzUwpvYnNlcnZlcjokMnkkMDUkNHV4M0lQWWpNLmd3VUpDTkVZTEFuLjNNVGxuZldRZzVzRS9kNS54QU1NSE8yQXEwOFpVM3kKYWRtaW46JDJ5JDA1JGRlbjZZZlhsYU9nOE9OSTMvbWhxTi4xa0lCUTExREVQMFV4WXNwaUtYN2xzeVp1R2k3V2M2CmVkaXRvcjokMnkkMDUkN0gvY2FPWlA1aS45Q2VLSDJ2REpnTzA5S3gvNXYvdHJlL1IvWWNoSURuOTQxRzh4bmdqTnEKZGV2ZWxvcGVyOiQyeSQwNSRhWXQxREhkRWI0Qmc4NUNTOVVqVWJlM0lTWVJCRXdITzlvd1dlT3BDY3VrRTR5WG0uSmZMaQo=
                kind: Secret
                metadata:
                  name: htpass-secret
                  namespace: openshift-config
                type: Opaque
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: htpassw-oauth-config
        spec:
          remediationAction: inform # will be overridden by remediationAction in parent policy
          severity: high
          namespaceSelector:
            exclude: ["kube-*"]
            include: ["default"]
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: config.openshift.io/v1
                kind: OAuth
                metadata:
                  name: cluster
                spec:
                  identityProviders:
                  - name: local_users
                    mappingMethod: claim 
                    type: HTPasswd
                    htpasswd:
                      fileData:
                        name: htpass-secret
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-local-users
placementRef:
  name: placement-policy-local-users
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-local-users
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-local-users
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: environment, operator: In, values: ["dev"]}
